name: generate-readme
inputs:
  output-path:
    description: Name of the file to write generated README contents.
    default: README-GENERATED.md
  name:
    description: Name of the image.
    default: ""
  location:
    description: Location of the image.
    default: ""
  exclude-tags:
    description: Comma-separated list of tags to exlcude (optional).
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        #repository: git@github.com:distroless/readme-generator.git
        path: readme-generator
    - name: Run readme-generator
      shell: bash
      run: |
        set -x
        set -o errexit -o nounset -o errtrace -o pipefail
        pushd readme-generator
        tree . && echo
        go build -o run .
        popd
        ./readme-generator/run \
          -name "${{ inputs.name }}" \
          -location "${{ inputs.location }}" \
          -exclude-tags "${{ inputs.exclude-tags }}" \
          | tee "${{ inputs.output-path }}"
