name: distroless-test
concurrency: distroless-test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Test that readme-generator works for some distroless images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make output directory
        run: |
          rm -rf output/
          mkdir output/

      # https://github.com/distroless/nginx
      - uses: distroless/readme-generator@main
        with:
          output-path: output/README-nginx.md
          repo: https://github.com/distroless/nginx
          name: nginx
          location: distroless.dev/nginx
          description: "A minimal nginx base image rebuilt every night from source."
          exclude-tags: 1.20.2,1.20,1.23.0

      - uses: actions/upload-artifact@v3
        with:
          name: distroless-readmes
          path: output/
